apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-adiciatlosi
  namespace: adiciatlosi
spec:
  project: default
  source:
    repoURL:  https://github.com/adi0300/argogolangnew.git
    targetRevision: main
    path: golang
  destination:
    server: https://kubernetes.default.svc
    namespace: adiciatlosi

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  